In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction import DictVectorizer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

In [8]:
#1.机器学习的DictVectorizer练习，文本分词，CountVectorizer, TfidfVectorizer练习
import jieba

data = [
    {'颜色': '红', '尺寸': '大', '价格': 100},
    {'颜色': '蓝', '尺寸': '中', '价格': 80},
    {'颜色': '红', '尺寸': '小', '价格': 50}
]
dict_vec = DictVectorizer(sparse=False)

print(dict_vec.fit_transform(data))
print(dict_vec.get_feature_names_out())

[[100.   0.   1.   0.   1.   0.]
 [ 80.   1.   0.   0.   0.   1.]
 [ 50.   0.   0.   1.   1.   0.]]
['价格' '尺寸=中' '尺寸=大' '尺寸=小' '颜色=红' '颜色=蓝']

In [7]:
documents = [
    "I love machine learning. Machine learning is interesting.",
    "I love coding. Coding is fun and useful.",
    "Machine learning and coding are my favorite skills."
]
count_vec = CountVectorizer(min_df=1, max_df=2)
df = pd.DataFrame(count_vec.fit_transform(documents).toarray(), columns=count_vec.get_feature_names_out())
df

documents = [
    "人生苦短，我喜欢 python", 
    "人生漫长，不用 python python",
    "人生漫漫，不用 python python python"
]

count_vec = CountVectorizer(min_df=1)
df = pd.DataFrame(count_vec.fit_transform(documents).toarray(), columns=count_vec.get_feature_names_out())
df

def jieba_tokenize(text):
    return " ".join(jieba.cut(text))

cut_documents = [jieba_tokenize(doc) for doc in documents]
cut_documents

count_vec = CountVectorizer(min_df=1)
df = pd.DataFrame(count_vec.fit_transform(cut_documents).toarray(), columns=count_vec.get_feature_names_out())
df

   python  不用  人生  喜欢  漫漫  漫长  苦短
0       1   0   1   1   0   0   1
1       2   1   1   0   0   1   0
2       3   1   1   0   1   0   0

In [6]:
documents = [
    "I love machine learning. Machine learning is interesting.",
    "I love coding. Coding is fun and useful.",
    "Machine learning and coding are my favorite skills."
]

tfidf = TfidfVectorizer(min_df=1,stop_words='english')

X = tfidf.fit_transform(documents)
df = pd.DataFrame(X.toarray(), columns=tfidf.get_feature_names_out())
df

,coding,favorite,fun,interesting,learning,love,machine,skills,useful
0,0.000000,0.00000,0.000000,0.401429,0.610594,0.305297,0.610594,0.00000,0.000000
1,0.687703,0.00000,0.452123,0.000000,0.000000,0.343851,0.000000,0.00000,0.452123
2,0.393511,0.51742,0.000000,0.000000,0.393511,0.000000,0.393511,0.51742,0.000000